spring.application.name=BootMVCProj01-FirstApp
#Embarded server port
server.port=4041
#Viewresolver inputs (prefix,sufix)for default internal resource view resolver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp